# Generated by Django 2.2.4 on 2019-08-12 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_organic_pizza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pizza_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_organic_pizza.PizzaType')),
            ],
        ),
    ]
