# Generated by Django 2.2.4 on 2019-08-12 05:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_organic_pizza', '0003_auto_20190812_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pizza_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_organic_pizza.Pizza')),
            ],
        ),
    ]
