# Generated by Django 2.2.4 on 2019-08-12 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_organic_pizza', '0005_auto_20190812_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='django_organic_pizza.Pizza'),
        ),
    ]
